# Generated by Django 3.0.1 on 2019-12-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateField(default='2019-12-21')),
                ('due_date', models.DateField(default='2019-12-21')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='todolist.Category')),
            ],
        ),
    ]
